### ISSUE TITLE
ImportWarning: Not importing directory '.../babel/localedata': missing __init__.py

### ISSUE THREAD

**Issue by quinox** [mitsuhiko/babel#109]
(This is the same as [#156](http://babel.edgewall.org/ticket/156) from the old tracker.)

Babel shows an import-warning when you've configured your warning settings. It can be fixed by renaming the folder ''localedata'' or renaming the file ''localedata.py'', this way the code is explicit in what to import.

To reproduce:

```python
cd /tmp

virtualenv virtual_156

. virtual_156/bin/activate

pip install babel
Downloading/unpacking babel
  Downloading Babel-1.3.tar.gz (3.4MB): 3.4MB downloaded
  ...

python -W error

Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import babel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/virtual_156/local/lib/python2.7/site-packages/babel/__init__.py", line 20, in <module>
    from babel.core import UnknownLocaleError, Locale, default_locale, \
  File "/tmp/virtual_156/local/lib/python2.7/site-packages/babel/core.py", line 14, in <module>
    from babel import localedata
ImportWarning: Not importing directory '/tmp/virtual_156/local/lib/python2.7/site-packages/babel/localedata': missing __init__.py
>>> 
```

**Comment by rasca** [comment]
+1 same happens here

**Comment by hector** [comment]
+1 happening to me also
If you guys want to preserve the name for the localedata.py and the localedata folder, just:
```mv localedata.py localedata/__init__.py```

**Comment by sils1297** [comment]
This was fixed on master with commit https://github.com/mitsuhiko/babel/commit/7d387f95f4f41ed646bcb2b4fa39dae4a601b6ce .

We're currently adressing some maintenance relevant CI, backporting and release issues so it might take a few weeks until we can make some kind of release out of that. This situation will hopefully improve in the future with automated development releases done on merge, see https://github.com/mitsuhiko/babel/issues/194 for more information.
