### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jmagnusson** [mitsuhiko/babel#158]
I know you're busy and all @mitsuhiko, but would it be possible for you to release a new version that hotfixes the error mentioned in #91 and [mitsuhiko/flask-babel#43](https://github.com/mitsuhiko/flask-babel/issues/43)? Without the fix proposed in the latter issue, the PO file generation fails in Python 3.4.

**Comment by alexander-emelyanov** [comment]
In Flask we trust...

**Comment by mkzero** [comment]
@mitsuhiko 

Seriously, this repo hasn't been updated in over a year and you don't even seem to care to give a quick comment on what whill happen to this repo. If you as the maint are not interested in maintaining anymore, at least orphan that package and make a notice in the README, so others know they shouldn't use it until someone will care for the package. That's basic developer decency and takes like 5 minutes...

**Comment by ser** [comment]
@mitsuhiko :-1:

**Comment by mitsuhiko** [comment]
I pushed out a new release.  See #166 for the maintenance question.
