### ISSUE TITLE
Adding support for Guarani

### ISSUE THREAD

**Issue by miltontony** [mitsuhiko/babel#159]
Can you clarify if and when Guarani(grn) will be supported by Babel?
Currently trying to parse this code throws an error
```python
from babel import Locale
Locale.parse('grn')
>> babel.core.UnknownLocaleError: unknown locale 'grn'
```

**Comment by benselme** [comment]
This part of Babel is just an interface to CLDR, a data repository managed
by the Unicode consortium. It seems like Guarani is, unfortunately, not
supported yet by CLDR so there is not much that the Babel project can do.

**Comment by erickwilder** [comment]
@miltontony as @benselme said, the specs should be at CLDR.
