### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by sils1297** [mitsuhiko/babel#166]
This repository seems pretty stale, could you make an announcement in the readme or so if you don't intend to maintain it anymore?

**Comment by daveoncode** [comment]
I was wondering too :P

**Comment by sils1297** [comment]
@mitsuhiko ?

**Comment by mitsuhiko** [comment]
Hi, sorry for the lack of feedback here.  I need help in maintaining this repository because I just have too much on my plate.  I pushed out a release with some bugfixes now but there is more to be done.  If someone is willing to help, please let me know.

**Comment by sils1297** [comment]
@mitsuhiko may I recomment doing a short statement in your readme that you're searching for help?

**Comment by erickwilder** [comment]
@mitsuhiko I really want to help. How can we do this?

**Comment by rohithpr** [comment]
Hey, I'm here from ericwilder's message on `irc#pocoo`. I'm interested in contributing to this project but I haven't used it in the past and there doesn't seem to be any "easy-fix" label here. Could someone please point me to an easy-fix issue so that I can get started?

**Comment by mitsuhiko** [comment]
Ideally I can give someone who uses Babel already and wants to help commit access to review pull requests and issues. The way this could work the best is if things are unclear from issues, you can send me a mail or reach me directly via instant messenger and I jump on here and help out.

**Comment by mitsuhiko** [comment]
The main issue is that the github notifications do not work for the number of projects I have. I'm drowning in things that come in and it's impossible for me to prioritize issues any longer :(

**Comment by rohithpr** [comment]
Oh! I'll take a look around and try to fix some bugs. I doubt if I can do what you're looking for though.

**Comment by erickwilder** [comment]
@sils1297 I'll try to help by reviewing the current open pull requests and issues.

**Comment by sils1297** [comment]
@erickwilder I'm trying to help you a bit with automation stuff to be able to process PRs faster and get the project more stable if you don't mind.

**Comment by erickwilder** [comment]
@sils1297 great! Will be awesome if we can do that.

**Comment by sils1297** [comment]
@erickwilder feel free to merge https://github.com/mitsuhiko/babel/pull/170 , will speed up builds by far. I'm available on #pocoo (user sils) right now if you want to talk to me, so we can discuss how to get this project up to speed. Alternatively at https://gitter.im/coala-analyzer/coala (sils1297).
