### ISSUE TITLE
Is there an option for defining namespaces?

### ISSUE THREAD

**Issue by mohammadaminalaee** [mitsuhiko/babel#173]
Is there a way to define namespaces in Flask Babel? Let's say I have the word "Submit" and I want two different translations for the word in different places, in the same language.

**Comment by sils1297** [comment]
@mohammadaminalaee thanks for your report!

Babel was barely maintained for some time and we're some new people trying to get it up to speed again. Because of this it might take some time until we're able to adress this bug.

**Comment by erickwilder** [comment]
@mohammadaminalaee I think Babel itself doesn't support this. You can take a look at the `flask_babel` extension, which have a `pgettext` function which allow you to do just that: different translations based on context:
https://github.com/mitsuhiko/flask-babel/blob/master/flask_babel/__init__.py#L484

I don't know if it's a key responsibility of Babel itself to address such functionality.

**Comment by mohammadaminalaee** [comment]
Thank you guys for your answers. Can you provide an example of pgettext() please?

**Comment by erickwilder** [comment]
@mohammadaminalaee 
If you're using `flask_babel` it's pretty straightforward:
```python
from flask_babel import pgettext

pgettext('first-place', 'Submit')
pgtettext('another-place', 'Submit')
```
This will generate two entries for `Submit` text to be translated.

For a pure Babel approach, take a look in the `NullTranslations.upgettext`[1], which does pretty the same thing.

[1] https://github.com/mitsuhiko/babel/blob/master/babel/support.py#L436
