### ISSUE TITLE
Measure test coverage

### ISSUE THREAD

**Issue by sils1297** [mitsuhiko/babel#178]
In a talk with @erickwilder we agreed that we'll want to measure test coverage to make this project more stable and enforce that it may not go down on merging a PR.

We'll probably want to use pytest-cov and submit the coverage to codecov.io.

**Comment by erickwilder** [comment]
@sils1297 
`pytest-cov` is enough. Let me know if you need some help on this.

**Comment by sils1297** [comment]
uhm everything's set up, codecov included. Any PR with a patch coverage below 80% will be marked as failed from now on. Overall coverage is 82%.
