### ISSUE TITLE
Avoid using reserved words in variable names

### ISSUE THREAD

**Issue by erickwilder** [mitsuhiko/babel#187]
This is a minor issue but we need to look at our code with care and avoid variable names such as `min` and `max` used in `babel.numbers.parse_precision()` function [1]

[1] https://github.com/mitsuhiko/babel/blob/master/babel/numbers.py#L549

**Comment by sils1297** [comment]
@erickwilder I plan to set up scrutinizer so we'll automatically get warnings if a PR introduces such things or other easily autodetectable things like unused imports.

**Comment by mitsuhiko** [comment]
`min` and `max` are not reserved words.  Please do not blacklist builtin names.  That is just going to make things confusing if Python later introduces another builtin.
