### ISSUE TITLE
crash reading file with UTF-8 BOM + "# coding: utf-8" (supported since python 2.5)

### ISSUE THREAD

**Issue by lepistone** [mitsuhiko/babel#189]
Reading such a file fails at

https://github.com/mitsuhiko/babel/blob/master/babel/util.py#L81

however, those files seem to be supported since 2.5:

https://bugs.python.org/issue1378022

Would you consider a patch to allow such files in babel?

Thanks!

**Comment by sils1297** [comment]
Sounds great, you plan to do a PR?

**Comment by lepistone** [comment]
Sure. I gave a look at what cpython does now, and it looks like it compares the BOM and the comment, which sounds reasonable to me.

https://github.com/python/cpython/blob/master/Parser/tokenizer.c#L333-L339

**Comment by sils1297** [comment]
Ah note that the code will also be tested against pypy so if they don't support that that will be a problem. We could make an interpreter branch though and only support that for CPython...

**Comment by lepistone** [comment]
I tried, and pypy seems to have the same behavior (crashes only if there is a BOM but the comment says `latin1`).

**Comment by sils1297** [comment]
Cool :)

2015-08-05 18:48 GMT+02:00 Leonardo Pistone <notifications@github.com>:
