### ISSUE TITLE
babel throws a type error on imports python 3.3/3.4 on windows 7

### ISSUE THREAD

**Issue by colost8rams** [mitsuhiko/babel#207]
I have just tried installing babel and I keep getting a type error when I try the first example on the homepage.  I've tried under fresh installs of both python 3.3 and 3.4.  here's the full traceback:

    Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:37:12) [MSC v.1600 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from babel.dates import format_datetime
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python33\lib\site-packages\babel\dates.py", line 28, in <module>
        from babel.util import UTC, LOCALTZ
      File "C:\Python33\lib\site-packages\babel\util.py", line 278, in <module>
        from babel import localtime
      File "C:\Python33\lib\site-packages\babel\localtime\__init__.py", line 21, in <module>
        from babel.localtime._win32 import _get_localzone
      File "C:\Python33\lib\site-packages\babel\localtime\_win32.py", line 18, in <module>
        tz_names = get_global('windows_zone_mapping')
      File "C:\Python33\lib\site-packages\babel\core.py", line 58, in get_global
        _global_data = pickle.load(fileobj)
    TypeError: an integer is required (got type str)

the issue seems to be caused when babel tries unpicling the global data.

is this a known bug?

**Comment by sils1297** [comment]
Hi @colost8rams, thanks for your report. We'll try to look at it as soon as possible, we still have problems keeping up with this repository though so it might take some time - sorry :/ Any help is appreciated.

**Comment by colost8rams** [comment]
This seems to be a duplicate of issue 174:  https://github.com/mitsuhiko/babel/issues/174

a quick workaround is to install the github branch of babel 2.0.  so, I `pip uninstall babel` and then `pip install git+https://github.com/mitsuhiko/babel.git@2.0` and ... so far so good.  seems the global_data on the pypi distribution was pickled in python 2 whereas the one on the github branch was pickled with python 3?

**Comment by sils1297** [comment]
@colost8rams yes, thanks this seems to be a duplicate.
