### ISSUE TITLE
Formatting of negative babel.util.FixedOffsetTimezone offsets

### ISSUE THREAD

**Issue by moreati** [mitsuhiko/babel#211]
- [ ] Definite bug A: `FixedOffsetTimezone` dosn't account for negative offsets when it creates a default zone name

    ```python
    >>> for offset in [0, 60, -60]:
    ...     print babel.util.FixedOffsetTimezone(offset).zone
    Etc/GMT+0
    Etc/GMT+60
    Etc/GMT+-60
    ```

- [ ] Possible bug B: Additonally the repr() is odd if the offset is negative

    ```
    >>> babel.util.FixedOffsetTimezone(-60)
    <FixedOffset "Etc/GMT+-60" -1 day, 23:00:00>
   ```

I'll submit a PR for A. Any opinions on B?

**Comment by moreati** [comment]
I also noticed FixedOffsetTimezone deals in minutes, whereas pytz deals in hours. I'm chalking that up as potentially inconsistent, but not a bug.

```python
>>> pytz.timezone('Etc/GMT+1')
<StaticTzInfo 'Etc/GMT+1'>
>>> pytz.timezone('Etc/GMT+60')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pytz/__init__.py", line 170, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: 'Etc/GMT+60'

```

**Comment by sils1297** [comment]
@moreati from a first glance you seem to mix up two or even three bug reports in one, could you split them up? (Same with the PR, we want commits to be atomic, one change is one commit.)

**Comment by moreati** [comment]
OK, I'll close this and open separate issues and PRs
