### ISSUE TITLE
FixedOffsetTimezone renders negative offsets incorrectly

### ISSUE THREAD

**Issue by moreati** [mitsuhiko/babel#214]
```python
>>> babel.util.FixedOffsetTimezone(-60).zone
Etc/GMT+-60
```

**Comment by sils1297** [comment]
This is a bug, change needs to be backported to the maintenance 2.0 branch, @moreati I guess you'll have a PR for this soon as you already had a commit solving this, can you submit that PR for both master and the maintenance 2.0 branch?

**Comment by moreati** [comment]
> can you submit that PR for both master and the maintenance 2.0 branch?

I'll try
