### ISSUE TITLE
TypeError while executing 'pybabel update ...' in Python 3.x

### ISSUE THREAD

**Issue by williamwu0220** [mitsuhiko/babel#91]
I installed babel in Python 3.4.0 env, and babel cannot work while using update sub-command as follows:

```
william$ pybabel update -i i18n/locale/message.pot  -l zh_TW -d i18n/locale/ -D i18n
updating catalog 'i18n/locale/zh_TW/LC_MESSAGES/i18n.po' based on 'i18n/locale/message.pot'
Traceback (most recent call last):
  File "/Users/william/venv/pyramid/bin/pybabel", line 9, in <module>
    load_entry_point('Babel==1.3', 'console_scripts', 'pybabel')()
  File "/Users/william/venv/pyramid/lib/python3.4/site-packages/babel/messages/frontend.py", line 1151, in main
    return CommandLineInterface().run(sys.argv)
  File "/Users/william/venv/pyramid/lib/python3.4/site-packages/babel/messages/frontend.py", line 665, in run
    return getattr(self, cmdname)(args[1:])
  File "/Users/william/venv/pyramid/lib/python3.4/site-packages/babel/messages/frontend.py", line 1130, in update
    width=options.width)
  File "/Users/william/venv/pyramid/lib/python3.4/site-packages/babel/messages/pofile.py", line 444, in write_po
    _write(comment_header + u'\n')
  File "/Users/william/venv/pyramid/lib/python3.4/site-packages/babel/messages/pofile.py", line 388, in _write
    fileobj.write(text)
TypeError: must be str, not bytes
```

My env:
python: 3.4.0
os: Debian Wheezy
Babel: 1.3

**Comment by williamwu0220** [comment]
Looks like this issue had been solved in master branch. Will there be any release plan in the near future? Or should we need to fork this project to make that happen? Please... :(

**Comment by torotil** [comment]
+1

**Comment by williamwu0220** [comment]
I created a new project Py3Babel forked from Babel: https://github.com/williamwu0220/py3babel/
Patches welcome..

**Comment by AnderUstarroz** [comment]
After your fix is it still compatible with Python 2? If that's the case I think you should make a pull request to merge it at some stage with the master branch. There is no point of having many developments in parallel.

**Comment by alissonperez** [comment]
+1. Make a release, please!!

**Comment by jmagnusson** [comment]
Have you abandoned the project, @mitsuhiko? Do you need contributors?

**Comment by mitsuhiko** [comment]
I need support for maintaining this project badly.  If someone is up for helping out with it, please contact me :)

**Comment by mitsuhiko** [comment]
This particular issue should be fixed however.

**Comment by jmagnusson** [comment]
Great news! I don't really know my way around the code of this project so I'll have to pass. Hope you find that special someone.
